apiVersion: v1
kind: Namespace
metadata:
  name: nnhntr
---
# Note the document index of the deployment is hard-coded in deploy.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nnhntr
  namespace: nnhntr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nnhntr
  template:
    metadata:
      labels:
        app: nnhntr
    spec:
      imagePullSecrets:
        - name: crhntr
      containers:
        - name: nnhntr
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: nnhntr
  namespace: nnhntr
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: nnhntr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: nnhntr
spec:
  tls:
    - hosts:
        - nataliehunterart.com
  rules:
    - host: nataliehunterart.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nnhntr
                port:
                  number: 8080
