apiVersion: v1
kind: Namespace
metadata:
  name: nnhntr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nnhntr
  namespace: nnhntr
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nnhntr
  template:
    metadata:
      labels:
        app: nnhntr
    spec:
      containers:
        - name: nnhntr
          env:
            - name: PORT
              value: "8080"
          image: ko://github.com/nnhntr/nataliehunterart.com
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: github-registry
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  name: nnhntr
  namespace: nnhntr
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: nnhntr
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: nnhntr
  namespace: nnhntr
spec:
  tls:
    - hosts:
        - nataliehunterart.com
  rules:
    - host: nataliehunterart.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nnhntr
                port:
                  number: 8080
